"""adjust_token_fields

Revision ID: 28ba5a1b9af3
Revises: f3fa3fd96621
Create Date: 2024-08-07 15:29:55.263645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28ba5a1b9af3'
down_revision: Union[str, None] = 'f3fa3fd96621'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('display_device_tokens', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'display_device_tokens', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'display_device_tokens', type_='foreignkey')
    op.drop_column('display_device_tokens', 'owner_id')
    # ### end Alembic commands ###
