"""tokens_fields_fix

Revision ID: a0a016f80809
Revises: 4b8cabeae827
Create Date: 2024-08-07 00:38:06.225761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0a016f80809'
down_revision: Union[str, None] = '4b8cabeae827'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('display_device_tokens', sa.Column('token_type', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('display_device_tokens', 'token_type')
    # ### end Alembic commands ###
